spring:
  application:
    name: operation
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/system?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://127.0.0.1:32768/operation?characterEncoding=UTF-8&useSSL=false
#  redis:
#    host: eureka-zuul
  redis:
    host: 127.0.0.1
    port: 32769
  rabbitmq:
    host: 127.0.0.1
    port: 32771
    username: root
    password: root
  thymeleaf:
    cache: false
server:
  port: 8901
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      galaxy:
        framework:
          capricorn:
            mapper: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka-zuul:8101/eureka/
feign:
  hystrix:
    enabled: true